In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('C:/Users/rkocherlakota/Desktop/AI/DataSets/50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [5]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [6]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [7]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
X

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)
X_test

array([[28663.76, 127056.21, 201126.82, 1],
       [0.0, 135426.92, 0.0, 0],
       [66051.52, 182645.56, 118148.2, 1],
       [123334.88, 108679.17, 304981.62, 0],
       [91992.39, 135495.07, 252664.93, 0],
       [165349.2, 136897.8, 471784.1, 2],
       [22177.74, 154806.14, 28334.72, 0],
       [1315.46, 115816.21, 297114.46, 1],
       [38558.51, 82982.09, 174999.3, 0],
       [67532.53, 105751.03, 304768.73, 1]], dtype=object)

In [9]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([ 74812.14788419,  45957.0185796 , 100411.9766159 , 155330.45180131,
       127314.44726377, 192299.43931389,  63830.29667314,  55714.63858572,
        84260.35472974, 110059.47662316])

In [11]:
r2_score(y_test,y_pred)

0.9794557471168575

In [12]:
y_pred1 = regressor.predict(X_train)
y_pred1

array([113507.89988129,  49841.01543464, 129543.91677313, 128970.30675581,
       113924.46717111,  98003.07999241, 116915.63525781, 182686.29330189,
       101900.64845509, 148985.38626422,  99399.41854674, 163901.21756636,
        98882.35531322, 188976.15157665, 100929.73805256,  90727.17575689,
        75101.18587786, 114912.34970476,  90739.37145205, 135691.56329714,
       172813.8196995 , 157999.65333296, 173733.16696962, 116755.41956897,
       110085.16734913,  70133.71618035, 116424.65350793,  70849.88771088,
        96813.79789416,  88252.66076317, 159680.37341312,  47994.00475273,
       136231.08185079, 129052.97039087,  59538.24272378, 114497.19007454,
       151147.11068904,  47020.31278485, 146100.1414279 ,  74659.14248408])

In [13]:
r2_score(y_train,y_pred1)

0.9397385736877049